spring.application.name=api
server.port=${PORT}
spring.datasource.url=${URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=${DRIVER}

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=${UPDATE}
spring.jpa.show-sql=${TRUE}
spring.jpa.properties.hibernate.dialect=${MYSQLDIALECT}
logging.level.org.springframework.security=DEBUG